### ISSUE TITLE
Problems with print2boox

### ISSUE THREAD

**Issue by Ryoga22** [deemstone/print2Boox#1]
I have a problem with web site send2boox.com. I can log in but the website don't find my boox nova2 with the website. Instead, I have no problem with the website push.boox.com.

I don't know what to do. 

Thank you

**Comment by deemstone** [comment]
Have you login on your nova2 with the same account ?
I am not the official supporter of Boox,  have no idea about this problem. 
You could get supported from Boox: <https://help.boox.com/hc/en-us>

**Comment by Ryoga22** [comment]
Hi. Answering your question, yes, I logged with the same account. I think that I know what is the problem. Here, in Europe, boox has discontinued the url send2boox.com and now they are using push.boox.com. It's the same web page but with another url. Maybe if the extension can be changed for European users to use push.boox.com, it will be fine.
Thanks

**Comment by deemstone** [comment]
> Maybe if the extension can be changed for European users to use push.boox.com,

@Ryoga22 I will try this weekend, hope to solve this problem. 🤗

**Comment by Ryoga22** [comment]
Hi.
I saw that you changed the extension. Thank you very much. Now I'm be able to connect to my boox . But when I tried to print something I have this error. I don't know if you will be able to see the picture. If you can't, tell me and I send you the message. 

Bye
Elvira
![IMG_20200608_152043](https://user-images.githubusercontent.com/66325833/84041782-25a84b00-a99c-11ea-9281-21dbcef4c9fc.jpg)

**Comment by deemstone** [comment]
@Ryoga22 Oh, Maybe the international site built on a different storage service. I need more time to inspect how they do "push" on push.boox.com . 

but , I had a problem , that I has no device of "international version". (My English is poor, hope you can understand .)

I had to read the code in push.boox.com, try to understand what they do on "Push". This will cost me a bit more time. Hope you can wait patiently for my progress.
![image](https://user-images.githubusercontent.com/180128/84049720-5b225800-a9df-11ea-8178-18e906d22a70.png)

**Comment by Ryoga22** [comment]
Ok, no problem at all. Don't worry about your English. Mine is as bad as yours XD.
Take your time, it's not a problem. I'm really interesting in this extension because it will help me a lot.
You can write me when you make any change and I can test it for you. 
Thanks for your time.
Bye
Elvira

**Comment by deemstone** [comment]
@Ryoga22 Need your help , testing this pack <https://send.firefox.com/download/96e99740f472a506/#lqWraaFxZMD4ek9kbPgXxA>

Disable the existing one Before testing, and follow this guide to install the new pack <https://ui.vision/howto/install-chrome-extension-from-file>

**Comment by Ryoga22** [comment]
Hi. I did it and it works!!! The little "problem" is the name of the pdf that it's generated. It's a long sequence of letters and numbers, but for me it's ok. 
This is the name of the pdf file generated

ACFrOgDkk8hiR95xIM4QJ-of-NKEXeaTh9-7EqcIhR8V_7Q9oWm6U7he8CS22E4DyG2hRm44vdfbE5112q2ni18Ifu9DYc54qD18KHLWH1AOvvASAkbDOzdGbRcISQsmAzhX_GRtgRtecPuYDEId.pdf

Thank you very much. You made my day!! 
When you release this version I will need to re-installed it?
Thanks again.
Elvira

**Comment by deemstone** [comment]
@Ryoga22 Really good news!  No thanks, Happy helping others. 
I had just submit the new version to google web store, waiting for review passed (maybe 1-3days). After that you can delete the beta version , that installed manually yesterday. And enable the old one, it should be auto updated by chrome.

But the filename of pdf is made up with the web page title. Next version, consider adding a " custom name " function. I will try to solve this problem. 🙂

**Comment by deemstone** [comment]
@Ryoga22 Another problem. Had fixed and will publish 0.0.7. But google forbid submitting new version when a version is pending review. Waiting for 0.0.6 review passed.

**Comment by Ryoga22** [comment]
Ok. I'll waiting for 0.0.7 version. Thank you for let me know.
