### ISSUE TITLE
the login status is invalid

### ISSUE THREAD

**Issue by kubiste** [deemstone/print2Boox#3]
It gives me all the time, even I am logged ok

**Comment by cbartondock** [comment]
I believe this is a duplicate of my issue; ONYX has changed the way their website stores login credentials as far as I can tell, probably to accommodate the 3.1 Firmware update.

**Comment by cbartondock** [comment]
Basically it seems userUid, userId, and userName are no longer stored locally in chrome's storage.

**Comment by deemstone** [comment]
> Basically it seems userUid, userId, and userName are no longer stored locally in chrome's storage.

As predicted! I will fix it this week ( I had found a new way getting the user info ).

**Comment by cbartondock** [comment]
Nice! Thanks. If it helps their api seems to have a /users endpoint

**Comment by cbartondock** [comment]
Need any help with this? I can try to work out how they are doing it and submit a pr if I figure it out.

**Comment by deemstone** [comment]
version 0.0.8 has been released , and ready for update on web store. Should have been fixed.
